# Generated by Django 4.2.25 on 2025-10-13 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0002_clientedominio'),
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Super admin tiene acceso total a todos los clientes'),
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cliente', 'Admin del Cliente'), ('empleado_cliente', 'Empleado del Cliente'), ('usuario_final', 'Usuario Final'), ('manager', 'Manager'), ('coach', 'Coach'), ('receptionist', 'Recepcionista')], help_text='Rol que tiene el usuario en este cliente específico', max_length=30)),
                ('activo', models.BooleanField(default=True, help_text='Si el acceso está activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que tiene acceso el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='clientes_core.cliente')),
                ('usuario', models.ForeignKey(help_text='Usuario que tiene acceso al cliente', on_delete=django.db.models.deletion.CASCADE, related_name='clientes_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'cliente'], name='auth_core_u_usuario_a662d9_idx'), models.Index(fields=['cliente', 'activo'], name='auth_core_u_cliente_f810fb_idx')],
                'unique_together': {('usuario', 'cliente', 'rol')},
            },
        ),
    ]
