# Generated by Django 4.2.25 on 2025-10-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0003_cliente_tipo_fe'),
        ('auth_core', '0002_usuario_is_super_admin_userclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('intent', models.CharField(choices=[('registro', 'Registro de Usuario'), ('reset_password', 'Reset de Contraseña'), ('cambio_email', 'Cambio de Email')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('expira', models.DateTimeField()),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece la verificación', on_delete=django.db.models.deletion.CASCADE, to='clientes_core.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'intent', 'usado'], name='auth_core_c_email_cde96a_idx'), models.Index(fields=['expira'], name='auth_core_c_expira_9da88c_idx')],
                'unique_together': {('email', 'intent', 'cliente')},
            },
        ),
    ]
