# Generated by Django 4.2.25 on 2025-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0003_codigoverificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cliente', 'Admin del Cliente'), ('empleado_cliente', 'Empleado del Cliente'), ('usuario_final', 'Usuario Final'), ('manager', 'Manager'), ('coach', 'Coach'), ('receptionist', 'Recepcionista'), ('medico_m1', 'Médico M1'), ('medico_m2', 'Médico M2'), ('medico_m3', 'Médico M3'), ('paciente', 'Paciente'), ('admin_establecimiento', 'Admin de Establecimiento'), ('admin_ministro_salud', 'Admin Ministro de Salud')], help_text='Rol que tiene el usuario en este cliente específico', max_length=30),
        ),
    ]
