# Generated by Django 4.2.23 on 2025-08-14 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes_core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('referente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='clientes_core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_turno', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comprobante_abono', models.ForeignKey(blank=True, help_text='Si el turno pertenece a un AbonoMes pagado, todos comparten este comprobante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='pagos_core.comprobanteabono')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_core.lugar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fecha', 'hora', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prestadores/fotos/')),
                ('activo', models.BooleanField(default=True)),
                ('nombre_publico', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='clientes_core.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloqueoTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lugar', models.ForeignKey(blank=True, help_text='Si es nulo, bloqueo afecta a todas las sedes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_core.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoBonificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('generado_automaticamente', models.BooleanField(default=False)),
                ('tipo_turno', models.CharField(max_length=50)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificaciones_emitidas_manual', to=settings.AUTH_USER_MODEL)),
                ('turno_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificaciones_emitidas', to='turnos_core.turno')),
                ('usado_en_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificacion_usada', to='turnos_core.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_bonificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno bonificado',
                'verbose_name_plural': 'Turnos bonificados',
                'indexes': [models.Index(fields=['usuario', 'usado'], name='turnos_core_usuario_4dced6_idx'), models.Index(fields=['tipo_turno', 'usado'], name='turnos_core_tipo_tu_8fc671_idx'), models.Index(fields=['usuario', 'tipo_turno', 'usado'], name='turnos_core_usuario_d61b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_core', to='turnos_core.lugar')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='turnos_core.prestador')),
            ],
            options={
                'unique_together': {('prestador', 'lugar', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
