# Generated by Django 4.2.23 on 2025-08-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_padel', '0004_add_turnos_prioridad'),
        ('turnos_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='abono_mes_prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_prioridad_directos', to='turnos_padel.abonomes'),
        ),
        migrations.AddField(
            model_name='turno',
            name='abono_mes_reservado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_reservados_directos', to='turnos_padel.abonomes'),
        ),
    ]
