# Generated by Django 4.2.23 on 2025-08-18 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos_padel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('clientes_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos_core', '0002_initial'),
        ('turnos_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='abono_mes_prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_prioridad_directos', to='turnos_padel.abonomes'),
        ),
        migrations.AddField(
            model_name='turno',
            name='abono_mes_reservado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_reservados_directos', to='turnos_padel.abonomes'),
        ),
        migrations.AddField(
            model_name='turno',
            name='comprobante_abono',
            field=models.ForeignKey(blank=True, help_text='Si el turno pertenece a un AbonoMes pagado, todos comparten este comprobante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='pagos_core.comprobanteabono'),
        ),
        migrations.AddField(
            model_name='turno',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='turno',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_core.lugar'),
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestador',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='clientes_core.cliente'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='clientes_core.cliente'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_core', to='turnos_core.lugar'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='turnos_core.prestador'),
        ),
        migrations.AddField(
            model_name='bloqueoturnos',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bloqueoturnos',
            name='lugar',
            field=models.ForeignKey(blank=True, help_text='Si es nulo, bloqueo afecta a todas las sedes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_core.lugar'),
        ),
        migrations.AddIndex(
            model_name='turnobonificado',
            index=models.Index(fields=['usuario', 'usado'], name='turnos_core_usuario_4dced6_idx'),
        ),
        migrations.AddIndex(
            model_name='turnobonificado',
            index=models.Index(fields=['tipo_turno', 'usado'], name='turnos_core_tipo_tu_8fc671_idx'),
        ),
        migrations.AddIndex(
            model_name='turnobonificado',
            index=models.Index(fields=['usuario', 'tipo_turno', 'usado'], name='turnos_core_usuario_d61b0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('fecha', 'hora', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('prestador', 'lugar', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
