# Generated by Django 4.2.23 on 2025-07-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('turnos_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lugar', models.ForeignKey(blank=True, help_text='Si es nulo, bloqueo afecta a todas las sedes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_core.lugar')),
            ],
        ),
    ]
