# Generated by Django 4.2.23 on 2025-08-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_padel', '0001_initial'),
        ('turnos_core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnobonificado',
            name='usado_en_abono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificaciones_usadas', to='turnos_padel.abonomes'),
        ),
    ]
