# Generated by Django 4.2.23 on 2025-07-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0002_bloqueoturnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
