# Generated by Django 4.2.23 on 2025-08-21 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos_core', '0003_turnobonificado_usado_en_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_afectado_id', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('bonificacion_emitida', models.BooleanField(default=False)),
                ('bonificacion_id', models.IntegerField(blank=True, null=True)),
                ('tipo_turno_usado', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('accion_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelacion_admin', to='turnos_core.turno')),
            ],
            options={
                'indexes': [models.Index(fields=['event_id', 'creado_en'], name='turnos_core_event_i_478366_idx')],
            },
        ),
    ]
