# Generated by Django 4.2.23 on 2025-09-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0004_cancelacionadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloqueoTurnos',
        ),
    ]
