# Generated by Django 4.2.24 on 2025-09-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0005_remove_bloqueo_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='reservado_para_abono',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
