# Generated by Django 4.2.24 on 2025-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0006_turno_reservado_para_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnobonificado',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
