# Generated by Django 4.2.24 on 2025-09-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('turnos_core', '0007_add_valor_moneda_turnobonificado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('fecha', 'hora', 'content_type', 'object_id', 'lugar')},
        ),
    ]
