# Generated by Django 4.2.24 on 2025-09-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('turnos_core', '0008_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('fecha', 'hora', 'content_type', 'object_id')},
        ),
    ]
