# Generated by Django 4.2.25 on 2025-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0009_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='categorias_centro_ethe',
            field=models.JSONField(blank=True, default=list, help_text="Categorías de centro ETHE: ['C1', 'C2', 'C3']"),
        ),
        migrations.AddField(
            model_name='turno',
            name='asistio',
            field=models.BooleanField(blank=True, help_text='null=no marcado, True=asistió, False=no asistió', null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_asistencia',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se marcó la asistencia', null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='observaciones_asistencia',
            field=models.TextField(blank=True, help_text='Observaciones sobre la asistencia del paciente'),
        ),
    ]
