import logging
from django.utils.deprecation import MiddlewareMixin

logger = logging.getLogger(__name__)

class LoggingMiddleware(MiddlewareMixin):
    """Log each request and response."""

    def process_request(self, request):
        """Log details about the incoming HTTP request.

        Args:
            request (HttpRequest): The request being processed.
        """
        logger.info(
            "Request: %s %s from %s", request.method, request.get_full_path(), request.META.get("REMOTE_ADDR")
        )

    def process_response(self, request, response):
        """Log details about the outgoing HTTP response.

        Args:
            request (HttpRequest): The original request.
            response (HttpResponse): Response generated by the view.

        Returns:
            HttpResponse: The same response passed in.
        """
        logger.info(
            "Response: %s %s %s", request.method, request.get_full_path(), response.status_code
        )
        return response
