# Generated by Django 4.2.23 on 2025-08-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_cliente', models.CharField(choices=[('padel', 'Club de Padel'), ('financiera', 'Financiera'), ('peluqueria', 'Peluquería')], default='padel', help_text='Define el tipo de negocio del cliente.', max_length=50)),
                ('theme', models.CharField(choices=[('classic', 'Classic Theme'), ('alt', 'Alternative Theme')], default='classic', help_text='Define el esquema visual general del cliente.', max_length=50)),
                ('color_primario', models.CharField(blank=True, max_length=20, null=True)),
                ('color_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_clientes/')),
                ('configuraciones_extras', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
