# Generated by Django 4.2.24 on 2025-09-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='clientes_core.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['hostname'], name='clientes_co_hostnam_ea448b_idx')],
            },
        ),
    ]
