# Generated by Django 4.2.25 on 2025-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0002_clientedominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_fe',
            field=models.CharField(choices=[('padel', 'Frontend de Padel'), ('canchas', 'Frontend de Canchas'), ('financiera', 'Frontend de Financiera'), ('peluqueria', 'Frontend de Peluquería')], default='padel', help_text='Define el tipo de frontend específico para este cliente.', max_length=50),
        ),
    ]
