# Generated by Django 4.2.25 on 2025-10-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0002_clientedominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_fe',
            field=models.CharField(choices=[('padel', 'Frontend Profesores Padel'), ('canchas', 'Frontend Administración Canchas'), ('medicina', 'Frontend Medicina'), ('superadmin', 'Frontend Super Admin')], default='padel', help_text='Define qué frontend debe servirse para este cliente.', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('padel', 'Club de Padel'), ('canchas', 'Administración Canchas'), ('medicina', 'Medicina'), ('superadmin', 'Super Admin'), ('financiera', 'Financiera'), ('peluqueria', 'Peluquería')], default='padel', help_text='Define el tipo de negocio del cliente.', max_length=50),
        ),
    ]
