# Generated by Django 4.2.25 on 2025-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0003_cliente_tipo_fe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_fe',
            field=models.CharField(choices=[('padel', 'Frontend de Padel'), ('canchas', 'Frontend de Canchas'), ('medicina', 'Frontend de Medicina'), ('superadmin', 'Frontend de Super Admin')], default='padel', help_text='Define el tipo de frontend específico para este cliente.', max_length=50),
        ),
    ]
