# Generated by Django 4.2.25 on 2025-10-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0004_alter_cliente_tipo_fe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('padel', 'Club de Padel'), ('financiera', 'Financiera'), ('peluqueria', 'Peluquería'), ('medicina', 'Medicina'), ('superadmin', 'Super Admin')], default='padel', help_text='Define el tipo de negocio del cliente.', max_length=50),
        ),
    ]
