# Generated by Django 4.2.25 on 2025-10-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_core', '0005_alter_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('padel', 'Club de Padel'), ('financiera', 'Financiera'), ('peluqueria', 'Peluquería'), ('medicina', 'Medicina'), ('ethe_medica', 'ETHE Médica'), ('superadmin', 'Super Admin')], default='padel', help_text='Define el tipo de negocio del cliente.', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_fe',
            field=models.CharField(choices=[('padel', 'Frontend de Padel'), ('canchas', 'Frontend de Canchas'), ('medicina', 'Frontend de Medicina'), ('ethe', 'Frontend ETHE'), ('superadmin', 'Frontend de Super Admin')], default='padel', help_text='Define el tipo de frontend específico para este cliente.', max_length=50),
        ),
    ]
