# Generated by Django 4.2.23 on 2025-08-18 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSedePadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('cbu_cvu', models.CharField(blank=True, max_length=30)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_padel', to='turnos_core.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoClasePadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('x1', 'Individual'), ('x2', '2 Personas'), ('x3', '3 Personas'), ('x4', '4 Personas')], max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('configuracion_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_clase', to='turnos_padel.configuracionsedepadel')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAbonoPadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('x1', 'Individual'), ('x2', '2 Personas'), ('x3', '3 Personas'), ('x4', '4 Personas')], max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('configuracion_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_abono', to='turnos_padel.configuracionsedepadel')),
            ],
        ),
        migrations.CreateModel(
            name='AbonoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('vencido', 'No pagado a tiempo'), ('cancelado', 'Cancelado')], default='pagado', max_length=20)),
                ('renovado', models.BooleanField(default=False, help_text='Se marca True si fue renovado con un abono del mes siguiente')),
                ('fecha_limite_renovacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_mensuales', to='turnos_core.prestador')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_mensuales', to='turnos_core.lugar')),
                ('tipo_abono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='turnos_padel.tipoabonopadel')),
                ('tipo_clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='turnos_padel.tipoclasepadel')),
                ('turnos_prioridad', models.ManyToManyField(blank=True, related_name='abonos_prioritarios', to='turnos_core.turno')),
                ('turnos_reservados', models.ManyToManyField(blank=True, related_name='abonos_confirmados', to='turnos_core.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tipoclasepadel',
            constraint=models.UniqueConstraint(fields=('configuracion_sede', 'codigo'), name='uq_tipo_clase_por_sede_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tipoabonopadel',
            constraint=models.UniqueConstraint(fields=('configuracion_sede', 'codigo'), name='uq_tipo_abono_por_sede_codigo'),
        ),
        migrations.AddIndex(
            model_name='abonomes',
            index=models.Index(fields=['usuario', 'anio', 'mes'], name='turnos_pade_usuario_de5f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='abonomes',
            index=models.Index(fields=['sede', 'prestador', 'anio', 'mes'], name='turnos_pade_sede_id_aa0080_idx'),
        ),
        migrations.AddConstraint(
            model_name='abonomes',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pagado'])), fields=('sede', 'prestador', 'anio', 'mes', 'dia_semana', 'hora'), name='uq_abono_mes_franja_pagada'),
        ),
    ]
