# Generated by Django 4.2.23 on 2025-07-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos_core', '0003_alter_turno_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos_core.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('sedes', models.ManyToManyField(related_name='profesores', through='turnos_padel.Disponibilidad', to='turnos_core.lugar')),
            ],
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='turnos_padel.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('profesor', 'lugar', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
