# Generated by Django 4.2.23 on 2025-08-14 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSedePadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('cbu_cvu', models.CharField(blank=True, max_length=30)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_padel', to='turnos_core.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoClasePadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('configuracion_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_clase', to='turnos_padel.configuracionsedepadel')),
            ],
        ),
        migrations.CreateModel(
            name='AbonoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='creado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_mensuales', to='turnos_core.prestador')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_mensuales', to='turnos_core.lugar')),
                ('tipo_clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='turnos_padel.tipoclasepadel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'anio', 'mes'], name='turnos_pade_usuario_de5f7f_idx'), models.Index(fields=['sede', 'prestador', 'anio', 'mes'], name='turnos_pade_sede_id_aa0080_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='abonomes',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['creado', 'pagado'])), fields=('sede', 'prestador', 'anio', 'mes', 'dia_semana', 'hora'), name='uq_abono_mes_franja_activa'),
        ),
    ]
