# Generated by Django 4.2.24 on 2025-09-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_padel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonomes',
            name='configuracion_personalizada',
            field=models.JSONField(blank=True, help_text="Configuración personalizada: [{'tipo_clase_id': 1, 'cantidad': 2, 'codigo': 'x1'}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='abonomes',
            name='tipo_clase',
            field=models.ForeignKey(blank=True, help_text='Tipo de clase fijo (para abonos simples). Null si es personalizado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='turnos_padel.tipoclasepadel'),
        ),
    ]
