# Generated by Django 4.2.23 on 2025-08-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0002_turno_abono_mes_prioridad_turno_abono_mes_reservado'),
        ('turnos_padel', '0004_add_turnos_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonomes',
            name='turnos_reservados',
            field=models.ManyToManyField(blank=True, related_name='abonos_confirmados', to='turnos_core.turno'),
        ),
    ]
