# Generated by Django 4.2.23 on 2025-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_padel', '0005_alter_abonomes_turnos_reservados'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonomes',
            name='renovado',
            field=models.BooleanField(default=False, help_text='Se marca True si fue renovado con un abono del mes siguiente'),
        ),
    ]
