# Generated by Django 4.2.23 on 2025-08-15 12:48

import apps.pagos_core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.pagos_core.models.comprobante_abono_upload_path)),
                ('hash_archivo', models.CharField(max_length=64, unique=True)),
                ('valido', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datos_extraidos', models.JSONField(blank=True, null=True)),
                ('nro_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('emisor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('emisor_cbu', models.CharField(blank=True, max_length=22, null=True)),
                ('emisor_cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_detectada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PagoIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pre_aprobado', 'Preaprobado'), ('rechazado', 'Rechazado'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20)),
                ('monto_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('alias_destino', models.CharField(max_length=100)),
                ('cbu_destino', models.CharField(blank=True, max_length=64, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('tiempo_expiracion', models.DateTimeField()),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id_transaccion_banco', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes_core.cliente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('cbu', models.CharField(max_length=22)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('monto_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_maximo_minutos', models.IntegerField(default=60)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_pago', to='clientes_core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.pagos_core.models.comprobante_upload_path)),
                ('hash_archivo', models.CharField(max_length=64, unique=True)),
                ('valido', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datos_extraidos', models.JSONField(blank=True, null=True)),
                ('nro_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('emisor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('emisor_cbu', models.CharField(blank=True, max_length=22, null=True)),
                ('emisor_cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_detectada', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='clientes_core.cliente')),
            ],
            options={
                'verbose_name': 'Comprobante de pago',
                'verbose_name_plural': 'Comprobantes de pago',
                'ordering': ('-created_at',),
            },
        ),
    ]
