# Generated by Django 4.2.23 on 2025-08-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_core', '0001_initial'),
        ('pagos_core', '0001_initial'),
        ('turnos_padel', '0001_initial'),
        ('turnos_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepago',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='turnos_core.turno'),
        ),
        migrations.AddField(
            model_name='comprobanteabono',
            name='abono_mes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='turnos_padel.abonomes'),
        ),
        migrations.AddField(
            model_name='comprobanteabono',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_abono', to='clientes_core.cliente'),
        ),
    ]
