# Generated by Django 4.2.23 on 2025-09-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos_core', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionPago',
        ),
    ]
