# Generated by Django 4.2.25 on 2025-10-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_core', '0006_add_historial_categoria'),
        ('turnos_core', '0010_add_asistencia_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.JSONField(default=list, help_text="Categorías que atiende: ['C1', 'C2', 'C3']")),
                ('nombre_centro', models.CharField(help_text="Nombre específico del centro (ej: 'Consultorios Hepatología')", max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Atención ETHE',
                'verbose_name_plural': 'Centros de Atención ETHE',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.JSONField(default=list, help_text="Lista de categorías: ['M1', 'M2', 'M3']")),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('especialidad_medica', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prestador', models.OneToOneField(help_text='Vincula al sistema de turnos existente', on_delete=django.db.models.deletion.CASCADE, related_name='medico_ethe', to='turnos_core.prestador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico_ethe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico ETHE',
                'verbose_name_plural': 'Médicos ETHE',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_actual', models.CharField(choices=[('C1', 'Categoría 1'), ('C2', 'Categoría 2'), ('C3', 'Categoría 3')], help_text='Categoría según último test realizado', max_length=2)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('domicilio_calle', models.CharField(max_length=255)),
                ('domicilio_ciudad', models.CharField(max_length=100)),
                ('domicilio_provincia', models.CharField(max_length=100)),
                ('domicilio_codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_seguimiento', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('obra_social', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('historial_categorias', models.JSONField(default=list, help_text="[{'categoria': 'C1', 'fecha': '...', 'motivo': '...'}, ...]")),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_ingresados', to='turnos_core.lugar')),
                ('medico_ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_ingresados', to='ethe_medica.medico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_ethe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente ETHE',
                'verbose_name_plural': 'Pacientes ETHE',
            },
        ),
        migrations.CreateModel(
            name='ProtocoloSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_paciente', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('frecuencia_dias', models.IntegerField(help_text='Cada cuántos días debe tener seguimiento')),
                ('configuracion', models.JSONField(default=dict, help_text='Configuración adicional del protocolo')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocolo de Seguimiento',
                'verbose_name_plural': 'Protocolos de Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_test', models.CharField(choices=[('POCUS', 'POCUS'), ('FIB4', 'FIB4'), ('FIBROSCAN', 'FIBROSCAN')], max_length=20)),
                ('resultado', models.CharField(max_length=50)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_realizacion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_realizados', to='turnos_core.lugar')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_realizados', to='ethe_medica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_tests', to='ethe_medica.paciente')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_realizados', to='turnos_core.turno')),
            ],
            options={
                'verbose_name': 'Resultado de Test',
                'verbose_name_plural': 'Resultados de Tests',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='JerarquiaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_origen', models.CharField(max_length=2)),
                ('categoria_destino', models.CharField(max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_anteriores', to='ethe_medica.centroatencion')),
                ('centro_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_siguientes', to='ethe_medica.centroatencion')),
            ],
            options={
                'verbose_name': 'Jerarquía de Centro',
                'verbose_name_plural': 'Jerarquías de Centros',
                'ordering': ['-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_anterior', models.CharField(blank=True, help_text='Categoría anterior del paciente', max_length=2, null=True)),
                ('categoria_nueva', models.CharField(help_text='Nueva categoría del paciente', max_length=2)),
                ('motivo', models.TextField(help_text='Motivo del cambio de categoría')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(blank=True, help_text='Médico que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ethe_medica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios_categoria', to='ethe_medica.paciente')),
                ('test_resultado', models.ForeignKey(blank=True, help_text='Test que causó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ethe_medica.resultadotest')),
            ],
            options={
                'verbose_name': 'Historial de Categoría',
                'verbose_name_plural': 'Historiales de Categorías',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admin_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos_admin', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos_ethe', to='clientes_core.cliente')),
            ],
            options={
                'verbose_name': 'Establecimiento ETHE',
                'verbose_name_plural': 'Establecimientos ETHE',
            },
        ),
        migrations.AddField(
            model_name='centroatencion',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_ethe', to='ethe_medica.establecimiento'),
        ),
        migrations.AddField(
            model_name='centroatencion',
            name='lugar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centro_atencion_ethe', to='turnos_core.lugar'),
        ),
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADO', 'Realizado'), ('NO_ASISTIO', 'No asistió'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ethe_medica.paciente')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethe_medica.protocoloseguimiento')),
            ],
            options={
                'ordering': ['-fecha_programada'],
                'indexes': [models.Index(fields=['paciente', 'estado'], name='ethe_medica_pacient_a81dfe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resultadotest',
            index=models.Index(fields=['paciente', '-fecha_realizacion'], name='ethe_medica_pacient_cc8d07_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadotest',
            index=models.Index(fields=['tipo_test'], name='ethe_medica_tipo_te_5a2495_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadotest',
            index=models.Index(fields=['centro'], name='ethe_medica_centro__bb00d8_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['categoria_actual'], name='ethe_medica_categor_493493_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['documento'], name='ethe_medica_documen_8ae1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo'], name='ethe_medica_activo_4b166a_idx'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['activo'], name='ethe_medica_activo_52695a_idx'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['matricula'], name='ethe_medica_matricu_622eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='jerarquiacentro',
            index=models.Index(fields=['centro_origen', 'activo'], name='ethe_medica_centro__32ee94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jerarquiacentro',
            unique_together={('centro_origen', 'centro_destino')},
        ),
        migrations.AddIndex(
            model_name='historialcategoria',
            index=models.Index(fields=['paciente', 'fecha_cambio'], name='ethe_medica_pacient_020347_idx'),
        ),
        migrations.AddIndex(
            model_name='establecimiento',
            index=models.Index(fields=['cliente', 'activo'], name='ethe_medica_cliente_58d8da_idx'),
        ),
        migrations.AddIndex(
            model_name='centroatencion',
            index=models.Index(fields=['establecimiento', 'activo'], name='ethe_medica_estable_0fd195_idx'),
        ),
    ]
