# Generated by Django 4.2.25 on 2025-10-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_core', '0010_add_asistencia_fields'),
        ('ethe_medica', '0001_add_historial_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroatencion',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_atencion_ethe', to='turnos_core.lugar'),
        ),
    ]
