# Generated by Django 4.2.25 on 2025-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethe_medica', '0002_alter_centroatencion_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='categorias',
            field=models.JSONField(default=list, help_text="Lista de categorías: ['C1', 'C2', 'C3']"),
        ),
    ]
